[2025-03-08T22:50:09.579+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-08T22:50:09.614+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: career_analytics_pipeline.validate_data manual__2025-03-08T22:50:02.168360+00:00 [queued]>
[2025-03-08T22:50:09.632+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: career_analytics_pipeline.validate_data manual__2025-03-08T22:50:02.168360+00:00 [queued]>
[2025-03-08T22:50:09.635+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-08T22:50:09.659+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): validate_data> on 2025-03-08 22:50:02.168360+00:00
[2025-03-08T22:50:09.666+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2025-03-08T22:50:09.671+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'career_analytics_pipeline', 'validate_data', 'manual__2025-03-08T22:50:02.168360+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/Careers_Data_Pipeline.py', '--cfg-path', '/tmp/tmpax0hx837']
[2025-03-08T22:50:09.677+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask validate_data
[2025-03-08T22:50:09.751+0000] {task_command.py:467} INFO - Running <TaskInstance: career_analytics_pipeline.validate_data manual__2025-03-08T22:50:02.168360+00:00 [running]> on host b128859cb372
[2025-03-08T22:50:10.091+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='career_analytics_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T22:50:02.168360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T22:50:02.168360+00:00'
[2025-03-08T22:50:10.093+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-08T22:50:10.139+0000] {warnings.py:110} WARNING - /opt/***/dags/Careers_Data_Pipeline.py:102: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  professionals_df = pd.read_json(ti.xcom_pull(key='professionals_df', task_ids='transform_data'))

[2025-03-08T22:50:10.194+0000] {warnings.py:110} WARNING - /opt/***/dags/Careers_Data_Pipeline.py:103: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  jobs_df = pd.read_json(ti.xcom_pull(key='jobs_df', task_ids='transform_data'))

[2025-03-08T22:50:10.225+0000] {warnings.py:110} WARNING - /opt/***/dags/Careers_Data_Pipeline.py:104: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  skills_df = pd.read_json(ti.xcom_pull(key='skills_df', task_ids='transform_data'))

[2025-03-08T22:50:10.252+0000] {warnings.py:110} WARNING - /opt/***/dags/Careers_Data_Pipeline.py:105: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  certifications_df = pd.read_json(ti.xcom_pull(key='certifications_df', task_ids='transform_data'))

[2025-03-08T22:50:10.281+0000] {warnings.py:110} WARNING - /opt/***/dags/Careers_Data_Pipeline.py:106: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  educations_df = pd.read_json(ti.xcom_pull(key='educations_df', task_ids='transform_data'))

[2025-03-08T22:50:10.316+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Careers_Data_Pipeline.py", line 139, in validate_data_task
    validate_data(jobs_df, certifications_df, educations_df, skills_df)
  File "/opt/airflow/dags/Careers_Data_Pipeline.py", line 118, in validate_data
    print(f"Invalid date format in {col} of {df.__name__}:")
                                             ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute '__name__'
[2025-03-08T22:50:10.347+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=career_analytics_pipeline, task_id=validate_data, run_id=manual__2025-03-08T22:50:02.168360+00:00, execution_date=20250308T225002, start_date=20250308T225009, end_date=20250308T225010
[2025-03-08T22:50:10.369+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-08T22:50:10.371+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task validate_data ('DataFrame' object has no attribute '__name__'; 118)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Careers_Data_Pipeline.py", line 139, in validate_data_task
    validate_data(jobs_df, certifications_df, educations_df, skills_df)
  File "/opt/airflow/dags/Careers_Data_Pipeline.py", line 118, in validate_data
    print(f"Invalid date format in {col} of {df.__name__}:")
                                             ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute '__name__'
[2025-03-08T22:50:10.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-08T22:50:10.445+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T22:50:10.459+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
